services:
  # aichatbase_app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: aichatbase_app
  #   ports:
  #     - "${PORT:-3000}:3000"
  #     - "5555:5555"
  #   environment:
  #     - NODE_ENV=development
  #     - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@aichatbase_db:5432/${DB_NAME}
  #     - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
  #     - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
  #     - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
  #     - NEXTAUTH_URL=${NEXTAUTH_URL}
  #     - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
  #     - R2_ACCOUNT_ID=${R2_ACCOUNT_ID}
  #     - R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
  #     - R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
  #     - R2_BUCKET=${R2_BUCKET}
  #     - OPENAI_API_KEY=${OPENAI_API_KEY}
  #   depends_on:
  #     - aichatbase_db
  #   volumes:
  #     - ./:/app
  #     - /app/.next
  #     # - /app/node_modules
  #   restart: unless-stopped

  aichatbase_db:
    image: postgres:15
    container_name: aichatbase_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"

volumes:
  postgres_data:
